name: CI
on: push
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-22.04']
        php: ['8.1', '8.2']
    name: Run CI build
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - uses: actions/checkout@v3

      - name: PHP version
        run: |
          php -v
          php -i
          php -m

      - name: Validate composer files
        run: composer validate --strict

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install

      - name: Run unit tests
        run: vendor/bin/phpunit

      - name: Run static analysis
        run: vendor/bin/psalm
